routes/web.php
    Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/', 'HomeController@index');
    Route::resource('/','EventController');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/dasboard', 'HomeController@admin_index')->name('admin.home');

    // Route Resource for Permission
    Route::patch('permissions/active/{id}', ['uses' => 'Admin\PermissionsController@active', 'as' => 'permissions.active']);
    Route::patch('permissions/inactive/{id}', ['uses' => 'Admin\PermissionsController@inactive', 'as' => 'permissions.inactive']);
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);

    // Route Resource for Role
    Route::patch('roles/active/{id}', ['uses' => 'Admin\RolesController@active', 'as' => 'roles.active']);
    Route::patch('roles/inactive/{id}', ['uses' => 'Admin\RolesController@inactive', 'as' => 'roles.inactive']);
    Route::resource('roles', 'Admin\RolesController');

    // Route Resource for User
    Route::resource('users', 'Admin\UsersController');


    // Route Resource for Home
    Route::get('home/admin_token/{token}', ['uses' => 'HomeController@admin_token', 'as' => 'home.admin_token']);

    // Pricing
    Route::get('pricing/index', ['uses' => 'Admin\DashboardController@index', 'as' => 'pricing.index']);
    Route::post('pricing/getMetalPrices', ['uses' => 'Admin\DashboardController@getMetalPrices', 'as' => 'pricing.getMetalPrices']);
    Route::post('pricing/saveGoldData', ['uses' => 'Admin\DashboardController@saveGoldData', 'as' => 'pricing.saveGoldData']);
    Route::post('pricing/savePlatinumData', ['uses' => 'Admin\DashboardController@savePlatinumData', 'as' => 'pricing.savePlatinumData']);
    Route::post('pricing/saveSilverData', ['uses' => 'Admin\DashboardController@saveSilverData', 'as' => 'pricing.saveSilverData']);
    Route::post('pricing/saveGoldPerGramPrice', ['uses' => 'Admin\DashboardController@saveGoldPerGramPrice', 'as' => 'pricing.saveGoldPerGramPrice']);
    Route::post('pricing/savePlatinumPerGramPrice', ['uses' => 'Admin\DashboardController@savePlatinumPerGramPrice', 'as' => 'pricing.savePlatinumPerGramPrice']);
    Route::post('pricing/saveSilverPerGramPrice', ['uses' => 'Admin\DashboardController@saveSilverPerGramPrice', 'as' => 'pricing.saveSilverPerGramPrice']);
    Route::post('pricing/getGoldPriceByApi', ['uses' => 'Admin\DashboardController@getGoldPriceByApi', 'as' => 'pricing.getGoldPriceByApi']);
    Route::post('pricing/getSilverPriceByApi', ['uses' => 'Admin\DashboardController@getSilverPriceByApi', 'as' => 'pricing.getSilverPriceByApi']);
    Route::post('pricing/getPriceByMetalUnit', ['uses' => 'Admin\DashboardController@getPriceByMetalUnit', 'as' => 'pricing.getPriceByMetalUnit']);



    //  Process 1
    Route::post('process1/create', ['uses' => 'Admin\Process1Controller@create', 'as' => 'process1.create']);
    Route::get('process1/index', ['uses' => 'Admin\Process1Controller@index', 'as' => 'process1.index']);
    Route::get('process1/allprocess1/{id}', ['uses' => 'Admin\Process1Controller@allprocess1', 'as' => 'process1.allprocess1']);
    Route::post('process1/editrow', ['uses' => 'Admin\Process1Controller@editrow', 'as' => 'process1.editrow']);
    Route::post('process1/fetchdata', ['uses' => 'Admin\Process1Controller@fetchdata', 'as' => 'process1.fetchdata']);
    Route::post('process1/deleterow', ['uses' => 'Admin\Process1Controller@deleterow', 'as' => 'process1.deleterow']);

    //  Process 2
    Route::post('process2/create', ['uses' => 'Admin\Process2Controller@create', 'as' => 'process2.create']);
    Route::get('process2/index', ['uses' => 'Admin\Process2Controller@index', 'as' => 'process2.index']);
    Route::get('process2/allprocess2/{id}', ['uses' => 'Admin\Process2Controller@allprocess2', 'as' => 'process2.allprocess2']);
    Route::post('process2/editrow', ['uses' => 'Admin\Process2Controller@editrow', 'as' => 'process2.editrow']);
    Route::post('process2/fetchdata', ['uses' => 'Admin\Process2Controller@fetchdata', 'as' => 'process2.fetchdata']);
    Route::post('process2/deleterow', ['uses' => 'Admin\Process2Controller@deleterow', 'as' => 'process2.deleterow']);

    //  Process 3
    Route::post('process3/create', ['uses' => 'Admin\Process3Controller@create', 'as' => 'process3.create']);
    Route::get('process3/index', ['uses' => 'Admin\Process3Controller@index', 'as' => 'process3.index']);
    Route::get('process3/allprocess3/{id}', ['uses' => 'Admin\Process3Controller@allprocess3', 'as' => 'process3.allprocess3']);
    Route::post('process3/editrow', ['uses' => 'Admin\Process3Controller@editrow', 'as' => 'process3.editrow']);
    Route::post('process3/fetchdata', ['uses' => 'Admin\Process3Controller@fetchdata', 'as' => 'process3.fetchdata']);
    Route::post('process3/deleterow', ['uses' => 'Admin\Process3Controller@deleterow', 'as' => 'process3.deleterow']);

    //  Process 3
    Route::post('process4/create', ['uses' => 'Admin\Process4Controller@create', 'as' => 'process4.create']);
    Route::get('process4/index', ['uses' => 'Admin\Process4Controller@index', 'as' => 'process4.index']);
    Route::get('process4/allprocess4/{id}', ['uses' => 'Admin\Process4Controller@allprocess4', 'as' => 'process4.allprocess4']);
    Route::post('process4/editrow', ['uses' => 'Admin\Process4Controller@editrow', 'as' => 'process4.editrow']);
    Route::post('process4/fetchdata', ['uses' => 'Admin\Process4Controller@fetchdata', 'as' => 'process4.fetchdata']);
    Route::post('process4/deleterow', ['uses' => 'Admin\Process4Controller@deleterow', 'as' => 'process4.deleterow']);

    //  Code
    Route::post('code/create', ['uses' => 'Admin\CodeController@create', 'as' => 'code.create']);
    Route::get('code/index', ['uses' => 'Admin\CodeController@index', 'as' => 'code.index']);
    Route::get('code/allcode/{id}', ['uses' => 'Admin\CodeController@allcode', 'as' => 'code.allcode']);
    Route::post('code/editrow', ['uses' => 'Admin\CodeController@editrow', 'as' => 'code.editrow']);
    Route::post('code/fetchdata', ['uses' => 'Admin\CodeController@fetchdata', 'as' => 'code.fetchdata']);
    Route::post('code/deleterow', ['uses' => 'Admin\CodeController@deleterow', 'as' => 'code.deleterow']);

    //  Heading
    Route::post('heading/create', ['uses' => 'Admin\HeadingController@create', 'as' => 'heading.create']);
    Route::get('heading/index', ['uses' => 'Admin\HeadingController@index', 'as' => 'heading.index']);
    Route::get('heading/allheading/{id}', ['uses' => 'Admin\HeadingController@allheading', 'as' => 'heading.allheading']);
    Route::post('heading/editrow', ['uses' => 'Admin\HeadingController@editrow', 'as' => 'heading.editrow']);
    Route::post('heading/fetchdata', ['uses' => 'Admin\HeadingController@fetchdata', 'as' => 'heading.fetchdata']);
    Route::post('heading/deleterow', ['uses' => 'Admin\HeadingController@deleterow', 'as' => 'heading.deleterow']);

    //  Sub Heading
    Route::post('subheading/create', ['uses' => 'Admin\SubHeadingController@create', 'as' => 'subheading.create']);
    Route::get('subheading/index', ['uses' => 'Admin\SubHeadingController@index', 'as' => 'subheading.index']);
    Route::get('subheading/allsubheading/{id}', ['uses' => 'Admin\SubHeadingController@allsubheading', 'as' => 'subheading.allsubheading']);
    Route::post('subheading/editrow', ['uses' => 'Admin\SubHeadingController@editrow', 'as' => 'subheading.editrow']);
    Route::post('subheading/fetchdata', ['uses' => 'Admin\SubHeadingController@fetchdata', 'as' => 'subheading.fetchdata']);
    Route::post('subheading/deleterow', ['uses' => 'Admin\SubHeadingController@deleterow', 'as' => 'subheading.deleterow']);

    //  Payment
    Route::post('payment/create', ['uses' => 'Admin\PaymentController@create', 'as' => 'payment.create']);
    Route::get('payment/index', ['uses' => 'Admin\PaymentController@index', 'as' => 'payment.index']);
    Route::get('payment/allpayment/{id}', ['uses' => 'Admin\PaymentController@allpayment', 'as' => 'payment.allpayment']);
    Route::post('payment/editrow', ['uses' => 'Admin\PaymentController@editrow', 'as' => 'payment.editrow']);
    Route::post('payment/fetchdata', ['uses' => 'Admin\PaymentController@fetchdata', 'as' => 'payment.fetchdata']);
    Route::post('payment/deleterow', ['uses' => 'Admin\PaymentController@deleterow', 'as' => 'payment.deleterow']);

    //  Customer
    Route::post('customer/create', ['uses' => 'Admin\CustomerController@create', 'as' => 'customer.create']);
    Route::get('customer/index', ['uses' => 'Admin\CustomerController@index', 'as' => 'customer.index']);
    Route::get('customer/allcustomer/{id}', ['uses' => 'Admin\CustomerController@allcustomer', 'as' => 'customer.allcustomer']);
    Route::post('customer/editrow', ['uses' => 'Admin\CustomerController@editrow', 'as' => 'customer.editrow']);
    Route::post('customer/fetchdata', ['uses' => 'Admin\CustomerController@fetchdata', 'as' => 'customer.fetchdata']);
    Route::post('customer/deleterow', ['uses' => 'Admin\CustomerController@deleterow', 'as' => 'customer.deleterow']);

    //  Ticket
    Route::post('ticket/create', ['uses' => 'Admin\TicketController@create', 'as' => 'ticket.create']);
    Route::get('ticket/index', ['uses' => 'Admin\TicketController@index', 'as' => 'ticket.index']);
    Route::get('ticket/add', ['uses' => 'Admin\TicketController@add', 'as' => 'ticket.add']);
    Route::get('ticket/allticket/{id}', ['uses' => 'Admin\TicketController@allticket', 'as' => 'ticket.allticket']);
    Route::post('ticket/editrow', ['uses' => 'Admin\TicketController@editrow', 'as' => 'ticket.editrow']);
    Route::post('ticket/fetchdata', ['uses' => 'Admin\TicketController@fetchdata', 'as' => 'ticket.fetchdata']);

app/Models/Admin/Process2.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Process2 extends Model
{
    use SoftDeletes;
    //
    protected $fillable = ['id',
        'name',
        'nameKey',
        'metal_type',
        'unit',
        'per_gram',
        'labour_charges',
        'created_by',
        'updated_by', 'deleted_by'];
    protected $table = 'process2';
}

app/Http/Controllers/Admin/Process2Controller.php
<?php


namespace App\Http\Controllers\Admin;

use App\Helpers\PermissionHelper as Per;
use App\Models\Admin\Process2;
use App\User;
use Illuminate\Http\Request;
use DB;
use Auth;
use Form;

class Process2Controller
{
    public function index()
    {
        if (! Per::has_permission('process2_details')) {
            return redirect()->route('home');
        }

        return view('admin.process2.index');
    }

    public function create(Request $request)
    {
        if (! Per::has_permission('process2_create')) {
            return redirect()->route('home');
        }

        $name=$request->name;
        $process2 = Process2::where('name',$name)->get();
        if(count($process2)>0)
        {
            session()->flash('success', 'Metal Already Exists.');
            return redirect()->route('admin.process2.index');
        }
        else
        {
            $data = $request->all();
            $current_date_time = \Carbon\Carbon::now();
            $current_date_time->timezone = config('global.time_zone');
            $data['created_by'] = Auth::user()->id;
            $data['user_id'] = Auth::user()->id;
            $data['created_at'] = $current_date_time;
            Process2::create($data);
            session()->flash('success', 'Record has been created successfully.');
            return redirect()->route('admin.process2.index');
        }

    }

    public function fetchdata(Request $request)
    {
        $data = Process2::where('id',$request['id'])->get();
        return response()->json($data);
    }

    public function editrow(Request $request)
    {
        if (! Per::has_permission('process2_edit')) {
            return redirect()->route('home');
        }
        $data = $request->all();
        $id = $request['id'];
        $current_date_time = \Carbon\Carbon::now();
        $current_date_time->timezone = config('global.time_zone');
        $data['updated_by'] = Auth::user()->id;
        $data['updated_at'] = $current_date_time;
        $process2_name=$request->name;
        $process2count = Process2::where('id','!=',$id)->where('name',$process2_name)->get();
        if(count($process2count)>0)
        {
            $response='repeat';
        }
        else if($data['name']=='' || $data['nameKey']==''|| $data['metal_type']==''|| $data['unit']==''|| $data['per_gram']==''|| $data['labour_charges']=='' )
        {
            $response='null';
        }
        else
        {
            $datas['updated_by'] = Auth::user()->id;
            Process2::where('id',$id)->update([
                'name'=>$request['name'],
                'nameKey'=>$request['nameKey'],
                'metal_type'=>$request['metal_type'],
                'unit'=>$request['unit'],
                'per_gram'=>$request['per_gram'],
                'labour_charges'=>$request['labour_charges'],
            ]);
            $response='success';

        }
        return response()->json($response);

    }

    public function deleterow(Request $request)
    {
        if (! Per::has_permission('process2_delete')) {
            return redirect()->route('home');
        }

        $id = $request->id;
        $process2s = Process2::where('id',$id)->forceDelete();
    }

    public function allprocess2(Request $request,$id)
    {
        $columns = array(
            0 =>'id',
            1 =>'name',
            2 =>'nameKey',
            3 =>'metal_type',
            4 =>'unit',
            5 =>'per_gram',
            6 =>'labour_charges',
            7=> 'options',
        );

        $totalData = Process2::count();

        $totalFiltered = $totalData;

        $limit = $request->input('length');
        $start = $request->input('start');
        $order = $columns[$request->input('order.0.column')];
        $dir = $request->input('order.0.dir');

        if(empty($request->input('search.value')))
        {
            $lists = Process2::offset($start)
                ->limit($limit)
                ->orderBy('name','asc')
                ->get();
        }
        else
        {
            $search = $request->input('search.value');
            $lists =  Process2::where('name', 'LIKE',"%{$search}%")
                ->offset($start)
                ->limit($limit)
                ->orderBy($order,$dir)
                ->get();

            $totalFiltered = Process2::where('name', 'LIKE',"%{$search}%")
                ->count();
        }

        $data = array();

        $i=1;
        if(!empty($lists)) {
            foreach ($lists as $list) {


                $nestedData['id'] = "&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$i;

                $nestedData['name'] = $list->name;
                $nestedData['nameKey'] = $list->nameKey;
                $nestedData['metal_type'] = $list->metal_type;
                $nestedData['unit'] = $list->unit;
                $nestedData['per_gram'] = $list->per_gram;
                $nestedData['labour_charges'] = $list->labour_charges;
                $options="";
                if (Per::has_permission('process2_delete')) {

                    $options .= "<a class='btn btn-sm btn-danger' style='cursor:pointer;color:white;margin-left:2px;' onclick='rowdelete(\"" . $list->id . "\",\"0\")' ><i class='fas fa-trash-alt' ></i></button>";

                }
                if (Per::has_permission('process2_edit')) {
                    $options .= "<a class='btn btn-sm btn-warning' role='button' data-toggle='modal' data-target='#modal-process2' style='cursor:pointer;margin-left:2px;' onclick='editrow(\"" . $list->id . "\")' ><i class='fas fa-edit' ></i></button>";
                }

                $nestedData['options'] = $options;
                $data[] = $nestedData;
                $i++;

            }
        }

        $json_data = array(
            "draw"            => intval($request->input('draw')),
            "recordsTotal"    => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data"            => $data
        );
        echo json_encode($json_data);

    }
}

resources/views/admin/process2/fields.blade.php
<div class="form-group  col-md-5 @if($errors->has('name')) has-error @endif">
    {!! Form::label('name', 'Name *', ['class' => 'control-label']) !!}
    {!! Form::text('name', old('name'), ['class' => 'form-control form-control-sm',  'placeholder' => 'Enter Name','required'=>'true','maxlength' =>100]) !!}
    {!! Form::text('update_id', null, ['class' => 'form-control form-control-sm', 'id'=>'update_id','hidden' => 'true']) !!}
    @if($errors->has('name'))
        <span class="help-block">
                                        {{ $errors->first('name') }}
                                    </span>
    @endif

</div>

<div class="form-group  col-md-5 @if($errors->has('nameKey')) has-error @endif">
    {!! Form::label('nameKey', 'Short Name *', ['class' => 'control-label']) !!}
    {!! Form::text('nameKey', old('nameKey'), ['class' => 'form-control form-control-sm',  'placeholder' => 'Enter Short Name','required'=>'true','maxlength' =>100]) !!}
    @if($errors->has('nameKey'))
        <span class="help-block">
                                        {{ $errors->first('nameKey') }}
                                    </span>
    @endif

</div>

<div class="form-group  col-md-5 @if($errors->has('metal_type')) has-error @endif">
    {!! Form::label('metal_type', 'Metal Type *', ['class' => 'control-label']) !!}
    {!! Form::select('metal_type',config('status.metal_type'), old('metal_type'), ['class' => 'form-control form-control-sm',  'placeholder' => 'Select Metal Type','required'=>'true','maxlength' =>100]) !!}
    @if($errors->has('metal_type'))
        <span class="help-block">
                                        {{ $errors->first('metal_type') }}
                                    </span>
    @endif

</div>

<div class="form-group  col-md-5 @if($errors->has('unit')) has-error @endif">
    {!! Form::label('unit', 'Unit *', ['class' => 'control-label']) !!}
    {!! Form::number('unit', old('unit'), ['class' => 'form-control form-control-sm',  'placeholder' => 'Enter Unit','required'=>'true','maxlength' =>100]) !!}
    @if($errors->has('unit'))
        <span class="help-block">
                                        {{ $errors->first('unit') }}
                                    </span>
    @endif

</div>

<div class="form-group  col-md-5 @if($errors->has('per_gram')) has-error @endif">
    {!! Form::label('per_gram', 'Per Gram *', ['class' => 'control-label']) !!}
    {!! Form::number('per_gram', old('per_gram'), ['class' => 'form-control form-control-sm',  'placeholder' => 'Enter Name Key','required'=>'true','maxlength' =>100]) !!}
    @if($errors->has('per_gram'))
        <span class="help-block">
                                        {{ $errors->first('per_gram') }}
                                    </span>
    @endif

</div>

<div class="form-group  col-md-5 @if($errors->has('labour_charges')) has-error @endif">
    {!! Form::label('labour_charges', 'Labour Charges *', ['class' => 'control-label']) !!}
    {!! Form::number('labour_charges', old('labour_charges'), ['class' => 'form-control form-control-sm',  'placeholder' => 'Enter Labour Charges','required'=>'true','maxlength' =>100]) !!}
    @if($errors->has('labour_charges'))
        <span class="help-block">
                                        {{ $errors->first('labour_charges') }}
                                    </span>
    @endif

</div>

resources/views/admin/process2/js.blade.php
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script type="text/javascript">

    $(".select2").select2({
        //placeholder: "Select a Name",
        allowClear: true
    });

</script>
<script type="text/javascript">

    $(document).ready(function ()
    {
        document.getElementById('add_process2').style.display = "block";
        document.getElementById('edit_process2').style.display = "none";
        $('#clearall').show();

        var table= $('#process2_datatables').DataTable({
            "pageLength": 25,
            "processing": true,
            "serverSide": true,
            "ajax":{
                "type": "GET",
                "url": "{{ route('admin.process2.allprocess2',['archive']) }}'",
                "dataType": "json",
                "data":{ _token: "{{csrf_token()}}"}

            },
            "columnDefs": [{
                orderable: false,
                "targets": '_all',
                "createdCell": function (td, cellData, rowData, row, col) {
                    $(td).css('padding-top', '2px')
                    $(td).css('padding-left', '8px')
                    $(td).css('padding-bottom', '2px')
                    $(td).css('padding-right', '8px')
                }
            }],
            "columns": [
                {
                    "className":      'details-control',
                    "data": "id"
                },
                { "data": "name" },
                { "data": "nameKey" },
                { "data": "metal_type" },
                { "data": "unit" },
                { "data": "per_gram" },
                { "data": "labour_charges" },
                {
                    "data": "options"
                },
            ],
            "order": [[1, 'asc']]

        });
    });

    var clearall = function ()
    {
        $('#save').attr('disabled', false);
        document.getElementById('add_process2').style.display = "block";
        $('#clearall').show();
        document.getElementById('edit_process2').style.display = "none";
        $('#process2_datatables').DataTable().ajax.reload();
        $('#name').val('');
        $('#nameKey').val('');
        $('#metal_type').val('');
        $('#unit').val('');
        $('#labour_charges').val('');
        $('#per_gram').val('');
    }

    // Delete row

    var rowdelete = function (id,find)
    {
        if(find=='0')
        {
            var title='You will not be able to revert this !';

        }
        swal({
            title: "Are you sure?",
            text: title,
            icon: "warning",
            buttons: [
                'No, cancel it!',
                'Yes, I am sure!'
            ],
            dangerMode: true,
        }).then(function(isConfirm) {
            if (isConfirm) {

                $.ajax({
                    type: 'POST',
                    url: '{{ route('admin.process2.deleterow') }}',
                    data: {
                        _token: '{{ csrf_token() }}',
                        id: id,
                    },
                    success: function (response) {
                        swal({
                            title: 'Deleted!',
                            text: 'Record has been Deleted Successfully.',
                            icon: 'success',
                            timer: 2000,
                            button: false,
                        }).then(function() {
                        });
                        clearall();
                    }
                });
            } else {
                swal("Cancelled", "Your data is safe :)", "error");
            }
        });
    };

    // Edit Row
    var updaterow = function ()
    {
        var id = $('#update_id').val();
        var nameKey=$('#nameKey').val();
        var name=$('#name').val();
        var metal_type=$('#metal_type').val();
        var unit=$('#unit').val();
        var per_gram=$('#per_gram').val();
        var labour_charges=$('#labour_charges').val();

        $.ajax({
            type: 'POST',
            url: '{{ route("admin.process2.editrow") }}',
            data: {
                _token: '{{ csrf_token() }}',
                id: id,
                nameKey: nameKey,
                name: name,
                metal_type: metal_type,
                unit: unit,
                per_gram: per_gram,
                labour_charges: labour_charges
            },

            success: function (response)
            {
                if(response=='success')
                {
                    swal({
                        title: 'Data Updated',
                        type: 'success',
                        text: 'Record has been Updated Successfully',
                        icon: 'success',
                        timer: 2000,
                        button: false,
                    }).then(
                        function () {},
                        // handling the promise rejection
                        function (dismiss) {
                            if (dismiss === 'timer') {
                            }
                        }
                    );
                    location.reload();
                }
                else if(response=='repeat')
                {
                    var title='Metal Already Exists.!';
                    swal("Type Again", title, "error");
                }
                else if(response=='null')
                {
                    var title='Some Fields Empty. Try Again!';
                    swal("Type Again", title, "error");
                }


                $('#process2_datatables').DataTable().ajax.reload();
            }
        });
    };

    var editrow = function (id) {
        $('#save').attr('disabled', true);

        $.ajax({
            type: 'POST',
            url: '{{ route('admin.process2.fetchdata') }}',
            data: {
                _token: '{{ csrf_token() }}',
                id: id,
            },

            success: function (response) {
                jQuery('html,body').animate({scrollTop:0},0);
                document.getElementById('add_process2').style.display = "none";
                document.getElementById('edit_process2').style.display = "block";
                document.getElementById('clearall').style.display = "block";
                $('#update_id').val(response[0].id);
                $('#nameKey').val(response[0].nameKey);
                $('#name').val(response[0].name);
                $('#metal_type').val(response[0].metal_type);
                $('#unit').val(response[0].unit);
                $('#per_gram').val(response[0].per_gram);
                $('#labour_charges').val(response[0].labour_charges);

            }
        });

    };

    var status_filter= function ()
    {
        $('#process2_datatables').DataTable().ajax.reload();
    }

</script>