routes/web.php
    Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/', 'HomeController@index');
    Route::resource('/','EventController');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/dasboard', 'HomeController@admin_index')->name('admin.home');

    // Route Resource for Permission
    Route::patch('permissions/active/{id}', ['uses' => 'Admin\PermissionsController@active', 'as' => 'permissions.active']);
    Route::patch('permissions/inactive/{id}', ['uses' => 'Admin\PermissionsController@inactive', 'as' => 'permissions.inactive']);
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);

    // Route Resource for Role
    Route::patch('roles/active/{id}', ['uses' => 'Admin\RolesController@active', 'as' => 'roles.active']);
    Route::patch('roles/inactive/{id}', ['uses' => 'Admin\RolesController@inactive', 'as' => 'roles.inactive']);
    Route::resource('roles', 'Admin\RolesController');

    // Route Resource for User
    Route::resource('users', 'Admin\UsersController');


    // Route Resource for Home
    Route::get('home/admin_token/{token}', ['uses' => 'HomeController@admin_token', 'as' => 'home.admin_token']);

    // Pricing
    Route::get('pricing/index', ['uses' => 'Admin\DashboardController@index', 'as' => 'pricing.index']);
    Route::post('pricing/getMetalPrices', ['uses' => 'Admin\DashboardController@getMetalPrices', 'as' => 'pricing.getMetalPrices']);
    Route::post('pricing/saveGoldData', ['uses' => 'Admin\DashboardController@saveGoldData', 'as' => 'pricing.saveGoldData']);
    Route::post('pricing/savePlatinumData', ['uses' => 'Admin\DashboardController@savePlatinumData', 'as' => 'pricing.savePlatinumData']);
    Route::post('pricing/saveSilverData', ['uses' => 'Admin\DashboardController@saveSilverData', 'as' => 'pricing.saveSilverData']);
    Route::post('pricing/saveGoldPerGramPrice', ['uses' => 'Admin\DashboardController@saveGoldPerGramPrice', 'as' => 'pricing.saveGoldPerGramPrice']);
    Route::post('pricing/savePlatinumPerGramPrice', ['uses' => 'Admin\DashboardController@savePlatinumPerGramPrice', 'as' => 'pricing.savePlatinumPerGramPrice']);
    Route::post('pricing/saveSilverPerGramPrice', ['uses' => 'Admin\DashboardController@saveSilverPerGramPrice', 'as' => 'pricing.saveSilverPerGramPrice']);
    Route::post('pricing/getGoldPriceByApi', ['uses' => 'Admin\DashboardController@getGoldPriceByApi', 'as' => 'pricing.getGoldPriceByApi']);
    Route::post('pricing/getSilverPriceByApi', ['uses' => 'Admin\DashboardController@getSilverPriceByApi', 'as' => 'pricing.getSilverPriceByApi']);
    Route::post('pricing/getPriceByMetalUnit', ['uses' => 'Admin\DashboardController@getPriceByMetalUnit', 'as' => 'pricing.getPriceByMetalUnit']);



    //  Process 1
    Route::post('process1/create', ['uses' => 'Admin\Process1Controller@create', 'as' => 'process1.create']);
    Route::get('process1/index', ['uses' => 'Admin\Process1Controller@index', 'as' => 'process1.index']);
    Route::get('process1/allprocess1/{id}', ['uses' => 'Admin\Process1Controller@allprocess1', 'as' => 'process1.allprocess1']);
    Route::post('process1/editrow', ['uses' => 'Admin\Process1Controller@editrow', 'as' => 'process1.editrow']);
    Route::post('process1/fetchdata', ['uses' => 'Admin\Process1Controller@fetchdata', 'as' => 'process1.fetchdata']);
    Route::post('process1/deleterow', ['uses' => 'Admin\Process1Controller@deleterow', 'as' => 'process1.deleterow']);

    //  Process 2
    Route::post('process2/create', ['uses' => 'Admin\Process2Controller@create', 'as' => 'process2.create']);
    Route::get('process2/index', ['uses' => 'Admin\Process2Controller@index', 'as' => 'process2.index']);
    Route::get('process2/allprocess2/{id}', ['uses' => 'Admin\Process2Controller@allprocess2', 'as' => 'process2.allprocess2']);
    Route::post('process2/editrow', ['uses' => 'Admin\Process2Controller@editrow', 'as' => 'process2.editrow']);
    Route::post('process2/fetchdata', ['uses' => 'Admin\Process2Controller@fetchdata', 'as' => 'process2.fetchdata']);
    Route::post('process2/deleterow', ['uses' => 'Admin\Process2Controller@deleterow', 'as' => 'process2.deleterow']);

    //  Process 3
    Route::post('process3/create', ['uses' => 'Admin\Process3Controller@create', 'as' => 'process3.create']);
    Route::get('process3/index', ['uses' => 'Admin\Process3Controller@index', 'as' => 'process3.index']);
    Route::get('process3/allprocess3/{id}', ['uses' => 'Admin\Process3Controller@allprocess3', 'as' => 'process3.allprocess3']);
    Route::post('process3/editrow', ['uses' => 'Admin\Process3Controller@editrow', 'as' => 'process3.editrow']);
    Route::post('process3/fetchdata', ['uses' => 'Admin\Process3Controller@fetchdata', 'as' => 'process3.fetchdata']);
    Route::post('process3/deleterow', ['uses' => 'Admin\Process3Controller@deleterow', 'as' => 'process3.deleterow']);

    //  Process 3
    Route::post('process4/create', ['uses' => 'Admin\Process4Controller@create', 'as' => 'process4.create']);
    Route::get('process4/index', ['uses' => 'Admin\Process4Controller@index', 'as' => 'process4.index']);
    Route::get('process4/allprocess4/{id}', ['uses' => 'Admin\Process4Controller@allprocess4', 'as' => 'process4.allprocess4']);
    Route::post('process4/editrow', ['uses' => 'Admin\Process4Controller@editrow', 'as' => 'process4.editrow']);
    Route::post('process4/fetchdata', ['uses' => 'Admin\Process4Controller@fetchdata', 'as' => 'process4.fetchdata']);
    Route::post('process4/deleterow', ['uses' => 'Admin\Process4Controller@deleterow', 'as' => 'process4.deleterow']);

    //  Code
    Route::post('code/create', ['uses' => 'Admin\CodeController@create', 'as' => 'code.create']);
    Route::get('code/index', ['uses' => 'Admin\CodeController@index', 'as' => 'code.index']);
    Route::get('code/allcode/{id}', ['uses' => 'Admin\CodeController@allcode', 'as' => 'code.allcode']);
    Route::post('code/editrow', ['uses' => 'Admin\CodeController@editrow', 'as' => 'code.editrow']);
    Route::post('code/fetchdata', ['uses' => 'Admin\CodeController@fetchdata', 'as' => 'code.fetchdata']);
    Route::post('code/deleterow', ['uses' => 'Admin\CodeController@deleterow', 'as' => 'code.deleterow']);

    //  Heading
    Route::post('heading/create', ['uses' => 'Admin\HeadingController@create', 'as' => 'heading.create']);
    Route::get('heading/index', ['uses' => 'Admin\HeadingController@index', 'as' => 'heading.index']);
    Route::get('heading/allheading/{id}', ['uses' => 'Admin\HeadingController@allheading', 'as' => 'heading.allheading']);
    Route::post('heading/editrow', ['uses' => 'Admin\HeadingController@editrow', 'as' => 'heading.editrow']);
    Route::post('heading/fetchdata', ['uses' => 'Admin\HeadingController@fetchdata', 'as' => 'heading.fetchdata']);
    Route::post('heading/deleterow', ['uses' => 'Admin\HeadingController@deleterow', 'as' => 'heading.deleterow']);

    //  Sub Heading
    Route::post('subheading/create', ['uses' => 'Admin\SubHeadingController@create', 'as' => 'subheading.create']);
    Route::get('subheading/index', ['uses' => 'Admin\SubHeadingController@index', 'as' => 'subheading.index']);
    Route::get('subheading/allsubheading/{id}', ['uses' => 'Admin\SubHeadingController@allsubheading', 'as' => 'subheading.allsubheading']);
    Route::post('subheading/editrow', ['uses' => 'Admin\SubHeadingController@editrow', 'as' => 'subheading.editrow']);
    Route::post('subheading/fetchdata', ['uses' => 'Admin\SubHeadingController@fetchdata', 'as' => 'subheading.fetchdata']);
    Route::post('subheading/deleterow', ['uses' => 'Admin\SubHeadingController@deleterow', 'as' => 'subheading.deleterow']);

    //  Payment
    Route::post('payment/create', ['uses' => 'Admin\PaymentController@create', 'as' => 'payment.create']);
    Route::get('payment/index', ['uses' => 'Admin\PaymentController@index', 'as' => 'payment.index']);
    Route::get('payment/allpayment/{id}', ['uses' => 'Admin\PaymentController@allpayment', 'as' => 'payment.allpayment']);
    Route::post('payment/editrow', ['uses' => 'Admin\PaymentController@editrow', 'as' => 'payment.editrow']);
    Route::post('payment/fetchdata', ['uses' => 'Admin\PaymentController@fetchdata', 'as' => 'payment.fetchdata']);
    Route::post('payment/deleterow', ['uses' => 'Admin\PaymentController@deleterow', 'as' => 'payment.deleterow']);

    //  Customer
    Route::post('customer/create', ['uses' => 'Admin\CustomerController@create', 'as' => 'customer.create']);
    Route::get('customer/index', ['uses' => 'Admin\CustomerController@index', 'as' => 'customer.index']);
    Route::get('customer/allcustomer/{id}', ['uses' => 'Admin\CustomerController@allcustomer', 'as' => 'customer.allcustomer']);
    Route::post('customer/editrow', ['uses' => 'Admin\CustomerController@editrow', 'as' => 'customer.editrow']);
    Route::post('customer/fetchdata', ['uses' => 'Admin\CustomerController@fetchdata', 'as' => 'customer.fetchdata']);
    Route::post('customer/deleterow', ['uses' => 'Admin\CustomerController@deleterow', 'as' => 'customer.deleterow']);

    //  Ticket
    Route::post('ticket/create', ['uses' => 'Admin\TicketController@create', 'as' => 'ticket.create']);
    Route::get('ticket/index', ['uses' => 'Admin\TicketController@index', 'as' => 'ticket.index']);
    Route::get('ticket/add', ['uses' => 'Admin\TicketController@add', 'as' => 'ticket.add']);
    Route::get('ticket/allticket/{id}', ['uses' => 'Admin\TicketController@allticket', 'as' => 'ticket.allticket']);
    Route::post('ticket/editrow', ['uses' => 'Admin\TicketController@editrow', 'as' => 'ticket.editrow']);
    Route::post('ticket/fetchdata', ['uses' => 'Admin\TicketController@fetchdata', 'as' => 'ticket.fetchdata']);

app/Models/Admin/Payment.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Payment extends Model
{
    use SoftDeletes;
    //
    protected $fillable = ['id',
        'heading_id',
        'sub_heading_id',
        'reference',
        'rate',
        'quantity',
        'amount',
        'payment_option',
        'user_id',
        'created_by',
        'updated_by', 'deleted_by'];
    protected $table = 'payment';
}

app/Http/Controllers/Admin/PaymentController.php
<?php


namespace App\Http\Controllers\Admin;

use App\Helpers\PermissionHelper as Per;
use App\Models\Admin\Heading;
use App\Models\Admin\Payment;
use App\Models\Admin\SubHeading;
use App\User;
use Illuminate\Http\Request;
use DB;
use Auth;
use Form;

class PaymentController
{
    public function index()
    {
        if (! Per::has_permission('payment_details')) {
            return redirect()->route('home');
        }

        $heading=Heading::get()->pluck('name','name');
        $subheading=SubHeading::get()->pluck('name','name');
        return view('admin.payment.index',compact('heading','subheading'));
    }

    public function create(Request $request)
    {
        if (! Per::has_permission('payment_create')) {
            return redirect()->route('home');
        }
            $data = $request->all();
            $current_date_time = \Carbon\Carbon::now();
            $current_date_time->timezone = config('global.time_zone');
            $data['created_by'] = Auth::user()->id;
            $data['created_at'] = $current_date_time;
            Payment::create($data);
            session()->flash('success', 'Record has been created successfully.');
            return redirect()->route('admin.payment.index');

    }

    public function fetchdata(Request $request)
    {
        $data = Payment::where('paymentID',$request['paymentID'])->get();
        return response()->json($data);
    }

    public function editrow(Request $request)
    {
        if (! Per::has_permission('payment_edit')) {
            return redirect()->route('home');
        }
        $data = $request->all();
        $paymentID = $request['paymentID'];
        $current_date_time = \Carbon\Carbon::now();
        $current_date_time->timezone = config('global.time_zone');
        $data['updated_by'] = Auth::user()->id;
        $data['updated_at'] = $current_date_time;

        if($data['paymentID']=='' || $data['heading']=='' || $data['subHeading']=='' || $data['reference']==''
            || $data['rate']=='' || $data['quantity']==''|| $data['amount']==''|| $data['payment_option']==''  )
        {
            $response='null';
        }
        else
        {
            $datas['updated_by'] = Auth::user()->id;
            Payment::where('paymentID',$paymentID)->update([
                'heading'=>$request['heading'],
                'subHeading'=>$request['subHeading'],
                'reference'=>$request['reference'],
                'rate'=>$request['rate'],
                'quantity'=>$request['quantity'],
                'amount'=>$request['amount'],
                'payment_option'=>$request['payment_option'],
            ]);
            $response='success';

        }
        return response()->json($response);

    }

    public function deleterow(Request $request)
    {
        if (! Per::has_permission('payment_delete')) {
            return redirect()->route('home');
        }

        $paymentID = $request->paymentID;
        $payments = Payment::where('paymentID',$paymentID)->forceDelete();
    }

    public function allpayment(Request $request,$paymentID)
    {
        $columns = array(
            0 =>'paymentID',
            1 =>'heading',
            2 =>'subHeading',
            3 =>'reference',
            4 =>'rate',
            5 =>'quantity',
            6 =>'amount',
            7 =>'payment_option',
            8=> 'options',
        );

        $totalData = Payment::count();

        $totalFiltered = $totalData;

        $limit = $request->input('length');
        $start = $request->input('start');
        $order = $columns[$request->input('order.0.column')];
        $dir = $request->input('order.0.dir');

        if(empty($request->input('search.value')))
        {
            $lists = Payment::offset($start)
                ->limit($limit)
                ->orderBy('reference','asc')
                ->get();
        }
        else
        {
            $search = $request->input('search.value');
            $lists =  Payment::where('reference', 'LIKE',"%{$search}%")
                ->offset($start)
                ->limit($limit)
                ->orderBy($order,$dir)
                ->get();

            $totalFiltered = Payment::where('reference', 'LIKE',"%{$search}%")
                ->count();
        }

        $data = array();

        $i=1;
        if(!empty($lists)) {
            foreach ($lists as $list)
            {

                $nestedData['paymentID'] = "&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;".$i;
                $nestedData['heading'] = $list->heading;
                $nestedData['subHeading'] = $list->subHeading;
                $nestedData['reference'] = $list->reference;
                $nestedData['rate'] = $list->rate;
                $nestedData['quantity'] = $list->quantity;
                $nestedData['amount'] = $list->amount;
                $nestedData['payment_option'] = $list->payment_option;
                $options="";
                if (Per::has_permission('payment_delete')) {

                    $options .= "<a class='btn btn-sm btn-danger' style='cursor:pointer;color:white;margin-left:2px;' onclick='rowdelete(\"" . $list->paymentID . "\",\"0\")' ><i class='fas fa-trash-alt' ></i></button>";

                }
                if (Per::has_permission('payment_edit')) {
                    $options .= "<a class='btn btn-sm btn-warning' role='button' data-toggle='modal' data-target='#modal-payment' style='cursor:pointer;margin-left:2px;' onclick='editrow(\"" . $list->paymentID . "\")' ><i class='fas fa-edit' ></i></button>";
                }

                $nestedData['options'] = $options;
                $data[] = $nestedData;
                $i++;

            }
        }

        $json_data = array(
            "draw"            => intval($request->input('draw')),
            "recordsTotal"    => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data"            => $data
        );
        echo json_encode($json_data);

    }
}

resources/views/admin/payment/fields.blade.php
<div class="form-group  col-md-3 @if($errors->has('heading')) has-error @endif">
    {!! Form::label('heading', 'Heading *', ['class' => 'control-label']) !!}
    {!! Form::select('heading', $heading,old('heading'), ['class' => 'form-control form-control-sm',  'placeholder' => 'Select heading','required'=>'true','maxlength' =>100]) !!}
    {!! Form::text('update_id', null, ['class' => 'form-control form-control-sm', 'id'=>'update_id','hidden' => 'true']) !!}
    @if($errors->has('heading'))
        <span class="help-block">
                                        {{ $errors->first('heading') }}
                                    </span>
    @endif

</div>

<div class="form-group  col-md-3 @if($errors->has('subHeading')) has-error @endif">
    {!! Form::label('subHeading', 'Sub Heading *', ['class' => 'control-label']) !!}
    {!! Form::select('subHeading',$subheading, old('subHeading'), ['class' => 'form-control form-control-sm',  'placeholder' => 'Select Sub Heading','required'=>'true','maxlength' =>100]) !!}
    @if($errors->has('subHeading'))
        <span class="help-block">
                                        {{ $errors->first('subHeading') }}
                                    </span>
    @endif

</div>

<div class="form-group  col-md-3 @if($errors->has('reference')) has-error @endif">
    {!! Form::label('reference', 'Reference *', ['class' => 'control-label']) !!}
    {!! Form::text('reference', old('reference'), ['class' => 'form-control form-control-sm',  'placeholder' => 'Enter Reference','required'=>'true','maxlength' =>100]) !!}
    @if($errors->has('reference'))
        <span class="help-block">
                                        {{ $errors->first('reference') }}
                                    </span>
    @endif

</div>
<div class="form-group  col-md-3 @if($errors->has('rate')) has-error @endif">
    {!! Form::label('rate', 'Rate *', ['class' => 'control-label']) !!}
    {!! Form::number('rate', old('rate'), ['class' => 'form-control form-control-sm',  'placeholder' => 'Enter Rate','required'=>'true','maxlength' =>100]) !!}
    @if($errors->has('rate'))
        <span class="help-block">
                                        {{ $errors->first('rate') }}
                                    </span>
    @endif

</div>
<div class="form-group  col-md-3 @if($errors->has('quantity')) has-error @endif">
    {!! Form::label('quantity', 'Quantity *', ['class' => 'control-label']) !!}
    {!! Form::number('quantity', old('quantity'), ['class' => 'form-control form-control-sm',  'placeholder' => 'Enter Quantity','required'=>'true','maxlength' =>100]) !!}
    @if($errors->has('quantity'))
        <span class="help-block">
                                        {{ $errors->first('quantity') }}
                                    </span>
    @endif

</div>
<div class="form-group  col-md-3 @if($errors->has('amount')) has-error @endif">
    {!! Form::label('amount', 'Amount *', ['class' => 'control-label']) !!}
    {!! Form::number('amount', old('amount'), ['class' => 'form-control form-control-sm',  'placeholder' => 'Enter Amount','required'=>'true','maxlength' =>100]) !!}
    @if($errors->has('amount'))
        <span class="help-block">
                                        {{ $errors->first('amount') }}
                                    </span>
    @endif

</div>
<div class="form-group  col-md-3 @if($errors->has('payment_option')) has-error @endif">
    {!! Form::label('payment_option', 'Payment Option *', ['class' => 'control-label']) !!}
    {!! Form::select('payment_option',config('status.payment_option'), old('payment_option'), ['class' => 'form-control form-control-sm',  'placeholder' => 'Select Payment Option','required'=>'true','maxlength' =>100]) !!}
    @if($errors->has('payment_option'))
        <span class="help-block">
                                        {{ $errors->first('payment_option') }}
                                    </span>
    @endif

</div>

resources/views/admin/payment/js.blade.php
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script type="text/javascript">

    $(".select2").select2({
        //placeholder: "Select a Name",
        allowClear: true
    });


</script>
<script type="text/javascript">

    $(document).ready(function ()
    {
        document.getElementById('add_payment').style.display = "block";
        document.getElementById('edit_payment').style.display = "none";
        $('#clearall').show();

        var table= $('#payment_datatables').DataTable({
            "pageLength": 25,
            "processing": true,
            "serverSide": true,
            "ajax":{
                "type": "GET",
                "url": "{{ route('admin.payment.allpayment',['archive']) }}'",
                "dataType": "json",
                "data":{ _token: "{{csrf_token()}}"}

            },
            "columnDefs": [{
                orderable: false,
                "targets": '_all',
                "createdCell": function (td, cellData, rowData, row, col) {
                    $(td).css('padding-top', '2px')
                    $(td).css('padding-left', '8px')
                    $(td).css('padding-bottom', '2px')
                    $(td).css('padding-right', '8px')
                }
            }],

            "columns": [
                {
                    "className":      'details-control',
                    "data": "paymentID"
                },
                { "data": "reference" },
                { "data": "heading" },
                { "data": "subHeading" },
                { "data": "rate" },
                { "data": "quantity" },
                { "data": "amount" },
                { "data": "payment_option" },
                {
                    "data": "options"
                },
            ],
            "order": [[1, 'asc']]

        });
    });

    var clearall = function ()
    {

        $('#save').attr('disabled', false);
        document.getElementById('add_payment').style.display = "block";
        $('#clearall').show();
        document.getElementById('edit_payment').style.display = "none";
        $('#payment_datatables').DataTable().ajax.reload();
        $('#heading').val('');
        $('#subHeading').val('');
        $('#reference').val('');
        $('#rate').val('');
        $('#quantity').val('');
        $('#amount').val('');
        $('#payment_option').val('');
    };

    // Delete row

    var rowdelete = function (paymentID,find)
    {
        if(find=='0')
        {
            var title='You will not be able to revert this !';

        }
        swal({
            title: "Are you sure?",
            text: title,
            icon: "warning",
            buttons: [
                'No, cancel it!',
                'Yes, I am sure!'
            ],
            dangerMode: true,
        }).then(function(isConfirm) {
            if (isConfirm) {

                $.ajax({
                    type: 'POST',
                    url: '{{ route('admin.payment.deleterow') }}',
                    data: {
                        _token: '{{ csrf_token() }}',
                        paymentID: paymentID,
                    },
                    success: function (response) {
                        swal({
                            title: 'Deleted!',
                            text: 'Record has been Deleted Successfully.',
                            icon: 'success',
                            timer: 2000,
                            button: false,
                        }).then(function() {
                        });
                        clearall();
                    }
                });
            } else {
                swal("Cancelled", "Your data is safe :)", "error");
            }
        });
    };

    // Edit Row
    var updaterow = function ()
    {

        var paymentID = $('#update_id').val();
        var heading=$('#heading').val();
        var subHeading=$('#subHeading').val();
        var reference=$('#reference').val();
        var rate=$('#rate').val();
        var quantity=$('#quantity').val();
        var amount=$('#amount').val();
        var payment_option=$('#payment_option').val();

        $.ajax({
            type: 'POST',
            url: '{{ route("admin.payment.editrow") }}',
            data: {
                _token: '{{ csrf_token() }}',
                paymentID: paymentID,
                reference: reference,
                heading: heading,
                subHeading: subHeading,
                rate: rate,
                quantity: quantity,
                amount: amount,
                payment_option: payment_option
            },

            success: function (response)
            {
                if(response=='success')
                {
                    swal({
                        title: 'Data Updated',
                        type: 'success',
                        text: 'Record has been Updated Successfully',
                        icon: 'success',
                        timer: 2000,
                        button: false,
                    }).then(
                        function () {},
                        // handling the promise rejection
                        function (dismiss) {
                            if (dismiss === 'timer') {
                            }
                        }
                    )
                }
                else if(response=='repeat')
                {
                    var title='Process Name Already Exists.!';
                    swal("Type Again", title, "error");
                }
                else if(response=='null')
                {
                    var title='Some Fields Empty. Try Again!';
                    swal("Type Again", title, "error");
                }


                $('#payment_datatables').DataTable().ajax.reload();
            }
        });
    };

    var editrow = function (paymentID) {
        $('#save').attr('disabled', true);

        $.ajax({
            type: 'POST',
            url: '{{ route('admin.payment.fetchdata') }}',
            data: {
                _token: '{{ csrf_token() }}',
                paymentID: paymentID,
            },

            success: function (response) {
                jQuery('html,body').animate({scrollTop:0},0);
                document.getElementById('add_payment').style.display = "none";
                document.getElementById('edit_payment').style.display = "block";
                document.getElementById('clearall').style.display = "block";
                $('#update_id').val(response[0].paymentID);
                $('#heading').val(response[0].heading);
                $('#subHeading').val(response[0].subHeading);
                $('#reference').val(response[0].reference);
                $('#rate').val(response[0].rate);
                $('#quantity').val(response[0].quantity);
                $('#amount').val(response[0].amount);
                $('#payment_option').val(response[0].payment_option);

            }
        });

    };

    var status_filter= function ()
    {
        $('#payment_datatables').DataTable().ajax.reload();
    }

</script>